### ISSUE TITLE
Multiple Tello Config Issue

### ISSUE THREAD

**Issue by cemoke** [anqixu/tello_driver#15]
Hi, I used two Tellos(not EDU) with your script with the help of two USB wi-fi dongles. However, when I disconnected and tried again with the same configuration, right now only one of the adapters can connect. (I changed the config files accordingly BTW). Is there something that I don't understand?

Also is there any method to stack all the wifi interfaces and Tellos to be connected to the same configuration file? What can I do to achieve that do you have any suggestions?

Your repo helped me a lot and I would be grateful if you can help me further.

**Comment by anqixu** [comment]
As far as I remember, the problem is that each and every tello has the same IP address (e.g. maybe something like 192.168.10.1), and their corresponding access point connects your computer's wifi onto the same subdomain (e.g. 192.168.10.something). So it wouldn't help if you had two separate USB wifi dongles, because both of them cannot be connected onto the same subdomain at the same time; that would create a conflict in IP routing.

I've previously had success doing something really complicated: use docker to create containers (which act like virtual machines) running a bidirectional IP port forwarder, and have each docker container connect to a single wifi dongle and to a specific tello machine. So it would look something like this:

host PC <- 172.0.1.1 --- 172.0.1.2 -> TCP/UDP relay in Docker container 1 <- 192.168.10.2 --- 192.168.10.1 -> Tello 1
host PC <- 172.0.2.1 --- 172.0.2.2 -> TCP/UDP relay in Docker container 2 <- 192.168.10.2 --- 192.168.10.1 -> Tello 2

There are several technical complexities to make this work, e.g. have docker run containers in privileged mode, running hardware / software connections in a specific order, etc. For more details see: https://github.com/anqixu/tello_driver/tree/master/wifi_docker_proxy

I haven't done this for several years, so I'm afraid this is probably the most help I can provide.

Good luck.

**Comment by xjp99v5** [comment]
Hi, thank you for your multi drones connections. I managed to connect 2 drones with 2 usb dongles but cannot takeoff the Tellos and obtain the video streams together. Any solutions for this? Thank you.
